spring:
  application:
    name: npulsone
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test
    username: kwak
    password: 1234
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show-sql: true
        dialect: org.hibernate.dialect.H2Dialect
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

